package vista;

import controlador.Registro;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Empleado;

/**
 *
 * @author sobarzolicandeo
 * @version 28-11-2021
 */
public class AgregarEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form AgregarEmpleado
     */
    public AgregarEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jbtnGroup_genero = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxt_numrut = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxt_dvrut = new javax.swing.JTextField();
        nombre = new javax.swing.JLabel();
        jtxt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jlbl_appaterno = new javax.swing.JLabel();
        jlbl_apmaterno = new javax.swing.JLabel();
        jtxt_appaterno = new javax.swing.JTextField();
        jtxt_apmaterno = new javax.swing.JTextField();
        jlbl_genero = new javax.swing.JLabel();
        jrdb_masculino = new javax.swing.JRadioButton();
        jrdb_femenino = new javax.swing.JRadioButton();
        jlbl_fecnac = new javax.swing.JLabel();
        jtxt_dianac = new javax.swing.JTextField();
        jtxt_mesnac = new javax.swing.JTextField();
        jtxt_anonac = new javax.swing.JTextField();
        jcbo_estcivil = new javax.swing.JComboBox<>();
        jlblb_estcivil = new javax.swing.JLabel();
        jtxt_fono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxt_direccion = new javax.swing.JTextArea();
        jtxt_diacont = new javax.swing.JTextField();
        jtxt_mescont = new javax.swing.JTextField();
        jtxt_anocont = new javax.swing.JTextField();
        jlbl_fechaCont = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbtn_agregar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("RUT");

        jLabel2.setText("-");

        nombre.setText("Nombre");

        jtxt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nombreActionPerformed(evt);
            }
        });

        jlbl_appaterno.setText("Apellido Paterno");

        jlbl_apmaterno.setText("Apellido Materno");

        jtxt_appaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_appaternoActionPerformed(evt);
            }
        });

        jlbl_genero.setText("Género");

        jbtnGroup_genero.add(jrdb_masculino);
        jrdb_masculino.setText("Masculino");
        jrdb_masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdb_masculinoActionPerformed(evt);
            }
        });

        jbtnGroup_genero.add(jrdb_femenino);
        jrdb_femenino.setText("Femenino");
        jrdb_femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdb_femeninoActionPerformed(evt);
            }
        });

        jlbl_fecnac.setText("Fecha Nacimiento");

        jtxt_dianac.setText("dd");
        jtxt_dianac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_dianacFocusGained(evt);
            }
        });
        jtxt_dianac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_dianacActionPerformed(evt);
            }
        });

        jtxt_mesnac.setText("mm");
        jtxt_mesnac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_mesnacFocusGained(evt);
            }
        });
        jtxt_mesnac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_mesnacActionPerformed(evt);
            }
        });

        jtxt_anonac.setText("aaaa");
        jtxt_anonac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_anonacFocusGained(evt);
            }
        });
        jtxt_anonac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_anonacActionPerformed(evt);
            }
        });

        jcbo_estcivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero(a)", "Casado(a)", "Viudo(a)", "Divorciado(a)" }));

        jlblb_estcivil.setText("Estado Civil");

        jtxt_fono.setText("123456789");
        jtxt_fono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_fonoFocusGained(evt);
            }
        });
        jtxt_fono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_fonoActionPerformed(evt);
            }
        });

        jLabel4.setText("Teléfono");

        jLabel5.setText("Dirección");

        jtxt_direccion.setColumns(20);
        jtxt_direccion.setLineWrap(true);
        jtxt_direccion.setRows(5);
        jtxt_direccion.setToolTipText("");
        jtxt_direccion.setWrapStyleWord(true);
        jtxt_direccion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jtxt_direccion);

        jtxt_diacont.setText("dd");
        jtxt_diacont.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_diacontFocusGained(evt);
            }
        });

        jtxt_mescont.setText("mm");
        jtxt_mescont.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_mescontFocusGained(evt);
            }
        });

        jtxt_anocont.setText("aaaa");
        jtxt_anocont.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_anocontFocusGained(evt);
            }
        });

        jlbl_fechaCont.setText("Fecha Contrato");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlbl_appaterno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jlbl_apmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jlbl_fecnac)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_genero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblb_estcivil, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbl_fechaCont, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtxt_nombre)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jtxt_numrut)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtxt_dvrut, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jtxt_apmaterno)
                        .addComponent(jtxt_appaterno)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jtxt_dianac, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtxt_mesnac, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jrdb_masculino))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jrdb_femenino))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtxt_anonac, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jtxt_fono)
                        .addComponent(jcbo_estcivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxt_diacont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt_mescont, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt_anocont, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_numrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jtxt_dvrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_appaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_appaterno))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_apmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbl_apmaterno))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrdb_masculino)
                    .addComponent(jrdb_femenino)
                    .addComponent(jlbl_genero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_fecnac)
                    .addComponent(jtxt_dianac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_mesnac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_anonac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblb_estcivil)
                    .addComponent(jcbo_estcivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_fono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_diacont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_mescont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_anocont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_fechaCont))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jbtn_agregar.setText("Agregar");
        jbtn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agregarActionPerformed(evt);
            }
        });

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jbtn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_agregar)
                    .addComponent(jButton1))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregarActionPerformed

        int fono;
        String numRut,dvRut,nombre,appaterno,apmaterno,genero,dianac,mesnac,anonac,fecNacStr,estCivil,direccion,diacont,mescont,anocont,fecContStr;
        Date fecNac,fecCont;
        
        numRut = this.jtxt_numrut.getText();
        dvRut = this.jtxt_dvrut.getText();
        nombre = this.jtxt_nombre.getText();
        appaterno = this.jtxt_apmaterno.getText();
        apmaterno = this.jtxt_apmaterno.getText();
        genero = this.jbtnGroup_genero.getSelection().getActionCommand();
        
        dianac = this.jtxt_dianac.getText();
        mesnac = this.jtxt_mesnac.getText();
        anonac = this.jtxt_anonac.getText();
        fecNacStr = anonac + "-" + mesnac + "-" + dianac;
        SimpleDateFormat formateo = new SimpleDateFormat("yyyy-MM-dd");
        try {
            fecNac = formateo.parse(fecNacStr);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Ingrese formato de fecha dd-mm-aaaa", "Validación", 2);
            this.jtxt_dianac.requestFocus();
            return;
        }
        
        estCivil = this.jcbo_estcivil.getSelectedItem().toString();
        fono = Integer.parseInt(this.jtxt_fono.getText());
        direccion = this.jtxt_direccion.getText();
        
        diacont = this.jtxt_diacont.getText();
        mescont = this.jtxt_mescont.getText();
        anocont = this.jtxt_anocont.getText();
        fecContStr = anocont + "-" + mescont + "-" + diacont;
        SimpleDateFormat formateoCont = new SimpleDateFormat("yyyy-MM-dd");
        try {
            fecCont = formateoCont.parse(fecContStr);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Ingrese formato de fecha dd-mm-aaaa", "Validación", 2);
            this.jtxt_dianac.requestFocus();
            return;
        }
       
        Empleado empleado = new Empleado(numRut,dvRut,nombre,appaterno,apmaterno,genero,fecNac,estCivil,fono,direccion,fecCont);

        Registro reg = new Registro();
        
        if (reg.buscarEmpleado(reg.buscarTodos(), numRut) == false) {
            if (reg.agregar(empleado)) {
                JOptionPane.showMessageDialog(this, "Se Agregó el empleado", "Información", 1);

            } else {
                JOptionPane.showMessageDialog(this, "No se Agregó el empleado", "Información", 0);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Empleado ya existe", "Información", 1);
        }
        
    }//GEN-LAST:event_jbtn_agregarActionPerformed

    private void jtxt_anonacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_anonacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_anonacActionPerformed

    private void jtxt_mesnacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_mesnacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_mesnacActionPerformed

    private void jtxt_dianacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_dianacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_dianacActionPerformed

    private void jrdb_femeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdb_femeninoActionPerformed
        this. jrdb_femenino.setActionCommand("Femenino");
    }//GEN-LAST:event_jrdb_femeninoActionPerformed

    private void jrdb_masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdb_masculinoActionPerformed
        this.jrdb_masculino.setActionCommand("Masculino");
    }//GEN-LAST:event_jrdb_masculinoActionPerformed

    private void jtxt_appaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_appaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_appaternoActionPerformed

    private void jtxt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_nombreActionPerformed

    private void jtxt_dianacFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_dianacFocusGained
        this.jtxt_dianac.setText("");
    }//GEN-LAST:event_jtxt_dianacFocusGained

    private void jtxt_mesnacFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_mesnacFocusGained
        this.jtxt_mesnac.setText("");
    }//GEN-LAST:event_jtxt_mesnacFocusGained

    private void jtxt_anonacFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_anonacFocusGained
        this.jtxt_anonac.setText("");
    }//GEN-LAST:event_jtxt_anonacFocusGained

    private void jtxt_fonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_fonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_fonoActionPerformed

    private void jtxt_fonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_fonoFocusGained
        this.jtxt_fono.setText("");
    }//GEN-LAST:event_jtxt_fonoFocusGained

    private void jtxt_diacontFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_diacontFocusGained
        this.jtxt_diacont.setText("");
    }//GEN-LAST:event_jtxt_diacontFocusGained

    private void jtxt_mescontFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_mescontFocusGained
        this.jtxt_mescont.setText("");
    }//GEN-LAST:event_jtxt_mescontFocusGained

    private void jtxt_anocontFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_anocontFocusGained
        this.jtxt_anocont.setText("");
    }//GEN-LAST:event_jtxt_anocontFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.ButtonGroup jbtnGroup_genero;
    private javax.swing.JButton jbtn_agregar;
    private javax.swing.JComboBox<String> jcbo_estcivil;
    private javax.swing.JLabel jlbl_apmaterno;
    private javax.swing.JLabel jlbl_appaterno;
    private javax.swing.JLabel jlbl_fechaCont;
    private javax.swing.JLabel jlbl_fecnac;
    private javax.swing.JLabel jlbl_genero;
    private javax.swing.JLabel jlblb_estcivil;
    private javax.swing.JRadioButton jrdb_femenino;
    private javax.swing.JRadioButton jrdb_masculino;
    private javax.swing.JTextField jtxt_anocont;
    private javax.swing.JTextField jtxt_anonac;
    private javax.swing.JTextField jtxt_apmaterno;
    private javax.swing.JTextField jtxt_appaterno;
    private javax.swing.JTextField jtxt_diacont;
    private javax.swing.JTextField jtxt_dianac;
    private javax.swing.JTextArea jtxt_direccion;
    private javax.swing.JTextField jtxt_dvrut;
    private javax.swing.JTextField jtxt_fono;
    private javax.swing.JTextField jtxt_mescont;
    private javax.swing.JTextField jtxt_mesnac;
    private javax.swing.JTextField jtxt_nombre;
    private javax.swing.JTextField jtxt_numrut;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables

}